#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=".env.local"
TOTAL_STAGES=6

banner "Vercel 프로젝트 연결 및 배포 파이프라인"

# ── Stage 1: CLI 준비 ───────────────────────────────────────────────────────
stage "Vercel CLI 준비"
if command -v vercel >/dev/null 2>&1; then
  note "vercel CLI가 이미 설치되어 있습니다: $(vercel --version)"
else
  say "vercel CLI를 devDependency로 설치합니다 (bun 사용)."
  bun add -D vercel
fi
VERCEL="bunx vercel"
note "이후 단계는 '$VERCEL' 명령으로 실행됩니다."

# ── Stage 2: 로그인 ─────────────────────────────────────────────────────────
stage "Vercel 로그인"
say "브라우저에서 매직링크로 로그인합니다. 이미 로그인되어 있으면 건너뜁니다."
if $VERCEL whoami >/dev/null 2>&1; then
  note "이미 로그인됨: $($VERCEL whoami 2>/dev/null)"
else
  $VERCEL login
fi

# ── Stage 3: 프로젝트 연결 ──────────────────────────────────────────────────
stage "저장소를 Vercel 프로젝트에 연결"
say "이 저장소를 Vercel 프로젝트로 링크(또는 신규 생성)합니다."
note "framework: Next.js, root directory는 Enter로 기본값(저장소 루트) 사용."
$VERCEL link
step "완료되면 .vercel/project.json이 생성됩니다."

# ── Stage 4: 환경변수 설정 ──────────────────────────────────────────────────
stage "환경변수 설정 (production / preview / development)"
say "$ENV_FILE 기준 5개 변수를 Vercel의 세 환경 모두에 등록합니다."
note "이미 ${ENV_FILE}에 값이 있으면 기본값으로 제안됩니다 (Enter로 그대로 사용)."

ask DATABASE_URL "DATABASE_URL (Neon 연결 문자열):"
ask KIS_BASE_URL "KIS_BASE_URL (모의투자 기본값 https://openapivts.koreainvestment.com:29443):"
ask_secret KIS_APP_KEY "KIS_APP_KEY:"
ask_secret KIS_APP_SECRET "KIS_APP_SECRET:"
ask_secret KIS_ACCOUNT_NO "KIS_ACCOUNT_NO:"

write_env DATABASE_URL "$DATABASE_URL"
write_env KIS_BASE_URL "$KIS_BASE_URL"
write_env KIS_APP_KEY "$KIS_APP_KEY"
write_env KIS_APP_SECRET "$KIS_APP_SECRET"
write_env KIS_ACCOUNT_NO "$KIS_ACCOUNT_NO"

for env_name in production preview development; do
  for var in DATABASE_URL KIS_BASE_URL KIS_APP_KEY KIS_APP_SECRET KIS_ACCOUNT_NO; do
    value="${!var}"
    if [[ -z "$value" ]]; then
      warn "건너뜀: $var ($env_name) — 값이 비어 있음"
      SKIPPED+=("$var ($env_name) — 값을 나중에 채우고 'vercel env add $var $env_name'로 등록")
      continue
    fi
    # 기존 값이 있으면 먼저 제거(idempotent), 실패해도 무시
    $VERCEL env rm "$var" "$env_name" -y >/dev/null 2>&1 || true
    if printf '%s' "$value" | $VERCEL env add "$var" "$env_name" >/dev/null 2>&1; then
      printf '  %s✓ set%s Vercel env %s (%s)\n' "$GREEN" "$RESET" "$var" "$env_name"
    else
      warn "Vercel env 설정 실패: $var ($env_name)"
      SKIPPED+=("Vercel env $var ($env_name) — 수동으로 'vercel env add $var $env_name' 실행 필요")
    fi
  done
done

# ── Stage 5: GitHub 연동 확인 ───────────────────────────────────────────────
stage "GitHub 연동 확인 (대시보드 조작 필요)"
say "Vercel-GitHub App 저장소 접근 권한은 CLI로 승인할 수 없습니다 — 대시보드에서 직접 확인하세요."
open_url "https://vercel.com/dashboard"
step "방금 연결한 프로젝트로 이동 → Settings → Git 탭을 엽니다."
step "'Connected Git Repository'가 flameware/before-buy로 표시되는지 확인합니다."
step "표시되지 않으면 'Connect Git Repository'를 눌러 GitHub App에 이 저장소 접근 권한을 승인합니다."
step "Production Branch가 'main'으로 설정되어 있는지 확인합니다."
if confirm "GitHub 저장소 연결과 Production Branch(main)를 확인했습니까?"; then
  note "GitHub 연동 확인 완료."
else
  SKIPPED+=("Vercel 대시보드에서 GitHub 저장소 연결 확인/승인")
fi

# ── Stage 6: 배포 트리거 확인 ───────────────────────────────────────────────
stage "배포 파이프라인 확인"
say "main 브랜치에 빈 커밋을 푸시해 배포가 자동으로 트리거되는지 확인합니다."
if confirm "지금 빈 커밋을 만들어 main에 푸시하시겠습니까?"; then
  git commit --allow-empty -m "chore: verify Vercel deploy pipeline"
  git push origin main
  note "푸시 완료. Vercel 대시보드의 Deployments 탭에서 새 배포가 시작되는지 확인하세요."
  open_url "https://vercel.com/dashboard"
  step "Deployments 탭에서 방금 푸시한 커밋으로 빌드가 시작/완료되는지 확인합니다."
  if confirm "배포가 성공적으로 트리거되고 완료되었습니까?"; then
    note "배포 파이프라인 확인 완료 — main 푸시 시 자동 배포됨."
  else
    SKIPPED+=("배포 실패 원인 확인 — Vercel 대시보드의 빌드 로그 확인")
  fi
else
  SKIPPED+=("main 푸시로 배포 트리거 확인 (준비되면 직접 수행)")
fi

finish
